### ISSUE TITLE
Respect last mode when toggling on terminal

### ISSUE THREAD

**Issue by krishnakumarg1984** [akinsho/toggleterm.nvim#222] opened 2022-05-05 21:23 UTC
I have configured `start_in_insert` to be `true` for ToggleTerm. However, I'd like a setting where we **start** the terminal in insert mode if opening it up for the first time. If reusing a previous terminal (i.e. by toggling (hiding &unhiding) it, then toggleterm should open in the last mode. i.e. if we hid it while in normal mode, it should open back in normal mode (preserving cursor position). Same for insert mode..

Here is a use case that justifies this request:

 - Let's say in a floating terminal we switch to normal mode, scroll up a few screens to read a lengthy output from a command (say a LaTeX build output with 15 errors). 
 - After scrolling to the top of the build output, we notice three unrelated errors in the source code that need to be fixed in the first few lines of output. We decide to address the first error, and toggle the floating terminal to edit the LaTeX source code to fix it.
 - Now, we decide to fix the second issue, which is a warning from the compiler, and I wish to refer to the warning message now. Since the cursor was in normal mode near the first error, it is only a small jump from there, and I expect the toggling of terminal to take me very close to where I wish to be
 - However, the terminal toggle reveals that I am back in insert mode at the bottom i.e. the current shell prompt, and I have to annoyingly scroll screenfuls of content just to get back to the second issue. It becomes tedious to repeat this dance ad-infinitum.

**Comment by akinsho** [comment] 2022-05-05 21:55
This sounds like a duplicate of #76, my comment there is still largely applicable, i.e. personally all for this feature, probably not going to implement this myself as amongst the 5+ plugins I maintain I have more than enough on my plate currently. Happy to guide a PR though

**Comment by akinsho** [comment] 2022-05-11 06:31
Closing as a duplicate. To re-iterate the main blocker here is that no one is stepping up to contribute this, and unfortunately it is being left to me and I do not have the time to do this myself. **PRs Welcome**

**Closed by akinsho** 2022-05-11 06:31 UTC
Labels: duplicate
