### ISSUE TITLE
[Bug] Use of Deprecated vim.highlight.create

### ISSUE THREAD

**Issue by JonMontgo** [akinsho/toggleterm.nvim#330] opened 2022-10-13 19:00 UTC
It seems `vim.highlight.create` has been deprecated in Neovim 0.9 and instead `vim.api.nvim_set_hl` should be used 

Currently I am getting the below deprecation notice
```
vim.highlight.create is deprecated, use vim.api.nvim_set_hl instead. See :h deprecated
This function will be removed in Nvim version 0.9
stack traceback:
        /usr/share/nvim/runtime/lua/vim/highlight.lua:14: in function 'create'
        ...k/packer/start/toggleterm.nvim/lua/toggleterm/colors.lua:99: in function 'set_highlights'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:359: in function 'setup'
        /home/foobar/.config/nvim/lua/terminal/init.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

**Comment by akinsho** [comment] 2022-10-13 20:03
This issue is a duplicate of another issue that was raised claiming the same problem, but it turned out that the user had failed to update the plugin to the latest version. The code that they are referenced had since been removed. The plugin doesn't currently use the API you're talking about

**Comment by gkzhb** [comment] 2022-10-14 03:38
I got the same problem here. And I found I had been using v1.* version of this plugin.

After using `*` tag for this plugin according to the latest README, the problem disappeared.

**Closed** 2022-10-14 07:37 UTC
