### ISSUE TITLE
Can't seem to start in insert mode in either horizontal or vertical direction (but works fine in float or tab direction)

### ISSUE THREAD

**Issue by RobertYost** [akinsho/toggleterm.nvim#405] opened 2023-02-27 20:40 UTC
As the title says, when i try and open up a terminal in the horizontal or vertical direction, my terminal will always start in 'nt' mode, regardless if I have `start_in_insert` set to true or not. I would assume this meant terminal-normal mode, but it doesn't seem to be, as pressing `i` doesn't switch to insert mode as I'd expect, it still inserts text (except for any characters that are bound to some other actions). However, this does not happen in float or tab direction - it works as expected. Here is my config:
```
require('toggleterm').setup {
  open_mapping = [[<C-\>]],
  direction = 'horizontal',
  size = 15,
  hide_numbers = true,
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = '1',
  start_in_insert = true,
  persist_size = true,
}
```

My config for toggling a floating terminal is:
```
local terminal = require('toggleterm.terminal).Terminal
...
local toggle_float = function()
  local float = terminal:new({direction = "float"})
  return float:toggle()
end
...
-- toggle_float bound to keybind using which-key
```

Any idea what could be causing this? Any other info that i should provide for this? Regardless of this issue, love this plugin, thank you for all of the good work!!

**Comment by akinsho** [comment] 2023-02-28 10:06
@RobertYost so I'm unable to reproduce this myself. As a first step I suggest trying a *minimal init.lua* i.e. `nvim -u <path/to/a/minimal/file>` this file should only contain loading toggleterm and nothing else. We can then see if it's a config issue or a plugin issue. I suspect it's a config issue and once you clarify that you can then debug your config and see.

**Comment by akinsho** [comment] 2023-03-05 10:25
@RobertYost gonna close this out for tidying up reasons but let me know if you find a reproduction and I'll re-open. It's hard to know which issues to work on if I have too many unactionable ones open

**Closed by akinsho** 2023-03-05 10:25 UTC

**Comment by icefed** [comment] 2023-04-14 10:58
I also encountered this issue and found that it was caused by this commit: https://github.com/akinsho/toggleterm.nvim/commit/98e15df2c838fe5c3cae1efa36fa5c255fc75aa8. The default behavior was changed, but setting `persist_mode` to `false` resolved the issue.
