### ISSUE TITLE
[Bug] cursor position is not expected

### ISSUE THREAD

**Issue by DG9Jww** [akinsho/toggleterm.nvim#244] opened 2022-06-15 13:41 UTC
Cursor position is not expected after openning terminal again.

-  This is the first time I open the terminal.Currently the cursor is below the window
<img src=https://user-images.githubusercontent.com/84201009/173838460-4627eac3-40cf-41c8-9803-69ed5f5c7990.png width=60% />

- And then when I closed the terminal and opened it again,the cursor will move to the bottom 
![image](https://user-images.githubusercontent.com/84201009/173838943-6c11d7ee-38f6-4158-8dc9-af22ece991d8.png)

- Interestingly,this only happened when I was in insert mode before I close the terminal.If I quit in normal mode,the coordinate of cursor is correct.

**Comment by akinsho** [comment] 2022-06-15 14:11
Hi @DG9Jww,

Since I do not experience this problem, and it hasn't been reported before, you need to *include a minimal init.lua/vim with steps to reproduce this problem exactly*. Without those, I won't be able to help and will have to close this issue

**Comment by DG9Jww** [comment] 2022-06-15 15:15
Hi @akinsho ,
Here is my config file
```lua
local Terminal = require("toggleterm.terminal").Terminal
require("toggleterm").setup{
     direction = "float",
     close_on_exit = true,
     shell = vim.o.shell,
     float_opts = {
            border = "double",   -- 'single' | 'double' | 'shadow' | 'curved' | ... other options supported by win open
            winblend = 0,
            highlights = {
                border = "Normal",
                background = "Normal",
            },
        },
}

local shell = psn.platform.is_windows and "pwsh -NoLogo" or vim.o.shell

local terminals = {}

terminals.default = Terminal:new({
    cmd = shell,
    direction = "float",
    -- function to run on opening the terminal
    on_open = function(term)
        vim.cmd("startinsert!")
        vim.api.nvim_buf_set_keymap(term.bufnr, "t", "<c-t>", "<cmd>close<CR>", { noremap = true, silent = true })
        -- press "jj" to enter normal mode when using terminal
        -- see :help terminal-input
        vim.api.nvim_buf_set_keymap(term.bufnr, "t", "jj", [[<C-\><C-n>]], { noremap = true, silent = true })
    end,
})

_G.toggle_terminal = function(name)
  terminals[name]:toggle()
end

vim.keymap.set('n', "<c-t>", "<cmd>lua toggle_terminal('default')<cr>")

**Comment by DG9Jww** [comment] 2022-06-16 13:23
Windows Terminal &&PowerShell 7.2.1

NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by akinsho** [comment] 2022-06-16 13:33
@DG9Jww I have a very similar setup that I use, and it doesn't cause this issue for me, but I'm not a Windows user so don't know if it relates to your shell. Can you please try using `bash` or something and seeing if this issue reproduces

**Closed** 2022-06-16 15:29 UTC
Labels: needs more info
