### ISSUE TITLE
Closing the terminal is slow

### ISSUE THREAD

**Issue by carlosdr02** [akinsho/toggleterm.nvim#372] opened 2022-12-18 10:58 UTC
Idk why, but when I close the terminal (e.g., by typing "exit" or by pressing "q" on _lazygit_) it takes arround a second to close. Idk if this is a performance issue (I don't think so) or maybe there is a way of making it instant?

**Comment by akinsho** [comment] 2022-12-18 23:16
@carlosdr02 this isn't really described a reproducible issue or include steps to reproduce. This sounds very much like a configuration issue, either with lazy git or your configuration. Locally I cannot see any such issue nor has anyone else reported this and there has been no change to this plugin in over a month, so very unlikely due to something I've done.

I'm going to close this out but if you are able to *reproduce this issue with a minimal init.lua* that I can also use to very the exact issue then re-post here.

**Closed by akinsho** 2022-12-18 23:16 UTC
