### ISSUE TITLE
E :315

### ISSUE THREAD

**Issue by caamittiwari** [akinsho/toggleterm.nvim#291] opened 2022-08-12 11:36 UTC
![Screenshot 2022-08-12 170155](https://user-images.githubusercontent.com/73481919/184346197-02b40ca6-361f-41fe-89a1-70df0ff3dac3.png)

**Comment by caamittiwari** [comment] 2022-08-12 11:38
it  happen  not  always  but   most   time

**Comment by akinsho** [comment] 2022-08-12 13:52
@caamittiwari this is unfortunately not a very well formulated issue, it does not contain steps to reproduce this issue with a minimal `init.lua`, nor does it explain what actions you take to reproduce this.

Judging for the message though, `ml_get: invalid lnum` is an upstream issue caused by neovim nightly and the most common reason is using `winbar` which is broken in neovim nightly and should not be used. I'm going to close this out since this is an upstream issue and probably a duplicate of #276

**Closed by akinsho** 2022-08-12 13:52 UTC

**Comment by caamittiwari** [comment] 2022-08-12 14:42
thanks  for  support
