### ISSUE TITLE
setup instructions for vim-plug 

### ISSUE THREAD

**Issue by fbouzemarene** [akinsho/toggleterm.nvim#370] opened 2022-12-15 17:05 UTC
i am new to neovim and using vim-plug, i could'nt make it work . plugin seems to be installed but after  i put the setup part on my init.vim file , there is some error when i start neovim . the plugin seems not recognized ...

some one can help ?

**Comment by akinsho** [comment] 2022-12-15 17:34
@fbouzemarene I haven't used vim-plug in quite a long time, so I can't help as I don't remember how it works. Please have a careful read through of that project's readme. AFAIK it should be something like `Plug 'akinsho/toggleterm.nvim'` and then after calling `plug#end()` you would call the `require('toggleterm').setup()`. As I mentioned though, this is vaguely from memory so might not be correct. Anyone else, feel free to step in, but I will close this out in (a day or so) as these sorts of issues tend to linger for a long time

**Comment by fbouzemarene** [comment] 2022-12-15 21:49
i followed the instructions ... here is what i get when starting neovim 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/18036831/207974286-d7355e76-0ac4-43c8-914c-12cc685b6494.png">

though toggleterm seems to be succesfully installed ( :PlugStatus command )

<img width="216" alt="image" src="https://user-images.githubusercontent.com/18036831/207974485-1b90f605-7690-4012-b8f4-1d0bd84a990d.png">

**Comment by akinsho** [comment] 2022-12-15 22:55
@fbouzemarene I really can't help you debug a plugin I don't use. It looks like the issue is maybe that you aren't putting your setup call in a lua heredoc whilst using a vimscript file. I appreciate that getting neovim setup can be challenging but this plugin's tracker isn't the best place to solve this. There are a lot of blog posts that explain setting up neovim and package manager's etc. Sorry but I can't spare the time to dig into config issues like this.

**Closed by akinsho** 2022-12-15 22:55 UTC
