### ISSUE TITLE
[question]: lazygit not rightly displayed

### ISSUE THREAD

**Issue by tristone13th** [akinsho/toggleterm.nvim#138] opened 2022-01-05 07:04 UTC
![f3d01299ce60e20ed823f5f11669df1](https://user-images.githubusercontent.com/17382962/148174479-7bfc1e2a-074d-4433-94d7-01d77e62e735.png)

OS: Windows 11.
This is my config, just set the direction to "closed".

```lua
require("toggleterm").setup({
    direction = "float",
})
```

**Comment by akinsho** [comment] 2022-01-05 10:07
@tristone13th I'm not able to reproduce this as is and so this issue doesn't provide me with anyway to solve this problem for you. In general an issue should not just be an image unless it fully explains itself which they rarely do. Does this issue reproduce with a minimal setup i.e. the default config.

**Comment by tristone13th** [comment] 2022-01-05 12:01
> @tristone13th I'm not able to reproduce this as is and so this issue doesn't provide me with anyway to solve this problem for you. In general an issue should not just be an image unless it fully explains itself which they rarely do. Does this issue reproduce with a minimal setup i.e. the default config.

I updated and listed my setup above, it is near to the default config. I think there may be some hidden causes for it, I will list them here when I find them.

**Comment by akinsho** [comment] 2022-05-20 21:14
Going to close this out since it's quite old now and I'm pretty sure this is not how toggleterm behaves in a minimal config.

**Closed by akinsho** 2022-05-20 21:14 UTC
