### ISSUE TITLE
Bug: something I do causes all of nvim to freeze, have to kill process

### ISSUE THREAD

**Issue by rickyelopez** [akinsho/toggleterm.nvim#376] opened 2022-12-27 16:27 UTC
Hi there,

Loving this plugin! Has really cleaned up my workflow!

Every once in a while (it has happened 4-5 times since I've been using this plugin in the last month) I do _something_ (some keyboard combination or something) in a toggleterm floating term that causes all of neovim to freeze up. I've gone through the outputs of `ps -ux` and killed everything that I could that isn't nvim, but it stays frozen. The only clue that I have as to what's going on here is this output on the terminal once I finally give up and kill nvim completely:

```
...nvim/plugged/toggleterm.nvim/lua/toggleterm/terminal.lua:283: Keyboard interruptstack traceback:^I[C]: in function 'nvim_buf_call'^I...nvim/plugged/toggleterm.nvim/lua/toggleterm/terminal.lua:283: in function 'scroll_bottom'^I...nvim/plugged/toggleterm.nvim/lua/toggleterm/terminal.lua:346: in function <...nvim/plugged/toggleterm.nvim/lua/toggleterm/terminal.lua:345>
```

I really don't know how much more info I can provide here, but please let me know what else I can give.

Toggleterm config:
```lua
require("toggleterm").setup({
    open_mapping = [[<c-\>]],
    float_opts = {
        border = "curved",
    },
    direction = "float",
})

local Terminal = require("toggleterm.terminal").Terminal
local lazygit = Terminal:new({
    cmd = "lazygit",
    count = 10,
    hidden = true,
    direction = "float",
    on_open = function(term)
        vim.api.nvim_buf_set_keymap(term.bufnr, "n", "q", "<cmd>close<CR>", { noremap = true, silent = true })
        vim.api.nvim_buf_set_keymap(term.bufnr, 't', 'q', [[<C-\><C-n>]], { noremap = true, silent = true })
    end,
})


function _G.set_terminal_keymaps()
  local opts = {buffer = 0}
  -- vim.keymap.set('t', 'q', [[<C-\><C-n>]], opts)
  -- vim.keymap.set('t', 'jk', [[<C-\><C-n>]], opts)
  vim.keymap.set('t', '<C-h>', [[<Cmd>wincmd h<CR>]], opts)
  vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]], opts)
  vim.keymap.set('t', '<C-k>', [[<Cmd>wincmd k<CR>]], opts)
  vim.keymap.set('t', '<C-l>', [[<Cmd>wincmd l<CR>]], opts)
end

-- use term://*toggleterm#* to apply to only toggleterm terminals
-- use term://* for all terminals
vim.cmd('autocmd! TermOpen term://*toggleterm#* lua set_terminal_keymaps()')



local M = {}

M.lazygitToggle = function()
    lazygit:toggle()
end

local map = require("utils").map

map("<leader>tl", M.lazygitToggle)

return M
```

So far this has only happened to me when in a regular toggleterm float (not the lazygit one I defined above) and it _seems_ to only happen when I try to close the terminal with `Ctrl+\`.

Would really love to figure this out, even if it's just a workaround, cause this is the only problem I've had with this otherwise excellent plugin! Any help is appreciated! Thanks

**Comment by rsdenijs** [comment] 2023-02-09 15:17
I have a similar experience. In my case, when I have a running command that I try to interrupt with ctrl-c, there is a chance nvim freezes. This only happens with toggleterms, not with regular nvim terminals.

**Comment by akinsho** [comment] 2023-02-09 15:45
Unfortunately there isn't a huge amount I can do based on these reports. Toggleterm essentially just manages putting a neovim terminal in a window it doesn't control the behaviour of the terminal at all really so if a process gets or something that usually isn't something that toggleterm is doing or can even see. It only starts the terminal and holds onto the process id so it can send it commands sometimes but it doesn't manage it.

I've not seen or heard anything about either of these problems and haven't made any changes to this plugin in quite a while as I've been busy so I don't think I'd have introduced any regressions recently.

**Comment by rickyelopez** [comment] 2023-02-10 04:54
Yeah I think ctrl+c is what's making it happen for me too. I haven't had this happen in my terminal on this machine ever, which is what leads me to believe that it is related to toggleterm. That being said, I haven't had it happen in a while, so that's nice.

**Comment by rickyelopez** [comment] 2023-02-22 00:13
Yeah pretty confident now that it's hitting ctrl+c immediately after hitting enter on a command that is causing this. Can't repro every time, but every time I've had it happen it's been because of this.

**Comment by akinsho** [comment] 2023-02-22 07:38
@rickyelopez this really seems likely to be an issue that relates to the underlying terminal and not to toggleterm itself since it doesn't really control the terminal behaviour there is an upstream issue in neovim relating to this that came off the back of #398 can you check if that covers your issue as well. Another thing to try to do is use the `:terminal` command yourself and see if the behaviour still reproduces there if so this is definitely an upstream issue

**Comment by akinsho** [comment] 2023-02-22 22:28
I really think this issue is not directly related to toggleterm but something that you are noticing through toggleterm. If you can verify this issue is not cause in normal plain `:terminal` and is only brought on by toggleterm then please post a repro here but otherwise I'll close this as for now it's completely impossible for me to do anything as I can't repro this

**Closed by akinsho** 2023-02-22 22:28 UTC

**Comment by rsdenijs** [comment] 2023-02-25 22:17
Makes sense to close it. If i get the time ill try to create a sequence to reproduce. I have never hit the issue with the builtin terminal though. I’ve been holding back on toggleterm for this reason. Anyway, will try to post more info at some point.

**Comment by belafonte** [comment] 2024-09-09 09:41
Hi @akinsho, i know the Issue is closed already and quite old, but just found and i think it still is an issue.

Today i only used the internal nvim terminal and i'am pretty sure that run into a situation where toggleterm would have been frozen.

The issue seems to be related to a SIGINT that the internal terminal is not picking up correctly which results in many SIGINT ^C characters in the terminal.

<img width="662" alt="image" src="https://github.com/user-attachments/assets/ebc9cddf-f80d-4f52-943c-fb7bb14f6aec">


Iam always using tmux in my nvim terminals also in toggleterm and every time when toggleterm was freezing, and i reattached to the tmux session afterwards, i saw those characters.

Somehow this situation seems to freeze toggleterm even though the internal terminal resumes fine afterwards.

Not sure how to further debug this though. 
Appreciate any hints.

I feel this issues exists quite some time already and i just tried to live with it...

**Comment by rickyelopez** [comment] 2024-09-10 21:33
fwiw, I haven't had this issue since this ticket was originally closed. I don't think I started doing anything differently, either. It just stopped happening.

**Comment by belafonte** [comment] 2024-09-11 14:22
Ok weird. 
I do have this error since many years.
But must be something with my setup then and not related to toggleterm.

Thanks
