### ISSUE TITLE
Error opening vertical,horizontal and tab terminals

### ISSUE THREAD

**Issue by alexmailo** [akinsho/toggleterm.nvim#268] opened 2022-07-15 23:29 UTC
- Error
`Error executing Lua callback: .../pack/packer/start/toggleterm.nvim/lua/toggleterm/ui.lua:141: E474: Invalid argument`

- Stack traceback
```
stack traceback:
        [C]: in function '__newindex'
        .../pack/packer/start/toggleterm.nvim/lua/toggleterm/ui.lua:141: in function 'hl_term'
        ...packer/start/toggleterm.nvim/lua/toggleterm/terminal.lua:414: in function 'open'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:67: in function 'smart_toggle'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:342: in function 'toggle'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:315: in function 'toggle_command'
        ...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:432: in function <...ite/pack/packer/start/toggleterm.nvim/lua/toggleterm.lua:432>
```
- `nvim --version`
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

- config 
```
require("toggleterm").setup{
  -- size can be a number or function which is passed the current terminal
  size = function(term)
    if term.direction == "horizontal" then
      return 15
    elseif term.direction == "vertical" then
      return  300
    end
  end,
  open_mapping = [[<c-\>]],
  hide_numbers = true, -- hide the number column in toggleterm buffers
  shade_filetypes = {},
  shade_terminals = true, -- NOTE: this option takes priority over highlights specified so if you specify Normal highlights you should set this to false
  shading_factor = 2, -- the degree by which to darken to terminal colour, default: 1 for dark backgrounds, 3 for light
  start_in_insert = true,
  insert_mappings = true, -- whether or not the open mapping applies in insert mode
  terminal_mappings = true, -- whether or not the open mapping applies in the opened terminals
  persist_size = true,
  persist_mode = true, -- if set to true (default) the previous terminal mode will be remembered
  direction = 'float',
  close_on_exit = true, -- close the terminal window when the process exits
  shell = vim.o.shell, -- change the default shell
  float_opts = {
    border = 'single',
	-- width = 100,
 --    height = 50,
    winblend = 3,
  },
  winbar = {
    enabled = false,
  },
}
```

I suspect it has something to do with `winbar` (even though it is disabled) cause it works just fine on nvim `0.8.0`

**Comment by akinsho** [comment] 2022-07-16 09:30
@alexmailo can you try again, this should be fixed after the most recent commit

**Comment by akinsho** [comment] 2022-07-16 12:43
Reports in a duplicate issue is that this is fixed so closing this out now. If anyone on the latest version still has this issue comment back here

**Closed by akinsho** 2022-07-16 12:43 UTC

**Comment by alexmailo** [comment] 2022-07-16 16:20
Doing a `:PackerUpdate` fixed it. Thank you very much.

**Comment by akinsho** [comment] 2022-08-22 16:14
@matcha1024 I can't reproduce this on the latest nightly. You'll need to provide more information or exact reproduction steps if winbar is disabled, or you are on the correct version of nightly with winbar enabled, you should not be seeing this error
