### ISSUE TITLE
[Feature] Accepting a float between 0 and 1 as the width / height of the terminal

### ISSUE THREAD

**Issue by Bekaboo** [akinsho/toggleterm.nvim#181] opened 2022-03-21 06:52 UTC
Currently floating windows only accept ints as the height and width of the terminal, though you can use `math.floor(0.8 * vim.o.columns)` or something else to set the height or width as a percentage of the window height / width, however floating window initialized with customized size does not change their width or height like those initialized with default settings.

Float term with default settings (autoresize):
![image](https://user-images.githubusercontent.com/76579810/159215832-71eb28ff-21f4-49bc-bb70-69363a749266.png)
![image](https://user-images.githubusercontent.com/76579810/159215856-eee750a4-acbc-4cf0-8ce6-436310629c7d.png)

Float term with `height = math.floor(0.8 * vim.o.lines)` and `width = math.floor(0.8 * vim.o.columns)` (no autoresize):
![image](https://user-images.githubusercontent.com/76579810/159216193-d5b153e7-d120-4f0b-ad21-2279a40257f1.png)
![image](https://user-images.githubusercontent.com/76579810/159216232-dabb2cb9-09ca-4f7f-b992-fa3be0869fb1.png)

**Comment by akinsho** [comment] 2022-03-21 07:42
@Bekaboo if I understand correctly, the exact issue is that using `vim.o.lines` and other calculations like that don't autoresize a floating terminal. This is probably because those values are read once on vim startup, i.e. they aren't dynamically calculated. Seems to me the feature request here is a mechanism to specify window size for floats that is re-evaluated. I'm not sure that I like the magic of 0 and 1 values or the clarity. I prefer the simplicity of just allowing the user to specify a function and that gets called to return the height and width.

If you're up for raising that PR, I can show you where to look for that

**Comment by akinsho** [comment] 2022-03-21 07:49
Actually just realised this is a duplicate of #168, so I'm going to close this in favour of that. Please feel free to continue chatting on there.

**Closed by akinsho** 2022-03-21 07:49 UTC

**Comment by Bekaboo** [comment] 2022-03-21 08:01
Ah, just realized that height and width can be functions, my fault.

**Comment by Bekaboo** [comment] 2022-03-21 08:02
> Actually just realised this is a duplicate of #168, so I'm going to close this in favour of that. Please feel free to continue chatting on there.

Ah, just realized that height and width can be functions, my fault.
