### ISSUE TITLE
ToggleTerm opens 2 terminals

### ISSUE THREAD

**Issue by DanielCardonaRojas** [akinsho/toggleterm.nvim#111] opened 2021-11-11 22:42 UTC
I've been using this plugin for a while but haven't been able to fix the following issue: 

After starting neovim the first 2 times I call ToggleTerm will result in 2 open terminals.

This is my config using packer: 

```lua
  use {
      "akinsho/toggleterm.nvim",
      config = function()
        require("toggleterm").setup{
          open_mapping = '<leader>;',
          start_in_insert = true,
        }
      end
  }

```

![image](https://user-images.githubusercontent.com/5472687/141379371-ff207de0-f6b8-47dc-9bcc-fa9d3e76f560.png)

after closing them ToggleTerm will work just fine.

**Comment by akinsho** [comment] 2021-11-11 23:21
@DanielCardonaRojas are you able to whittle this down to a minimal configuration. Based on the description you've given I can't/won't be able to narrow this down. If you can get a minimal init.lua running with only this plugin that reproduces this issue then I can try and help. In all likelihood though it sounds like something else in your config is causing this interaction since it doesn't reproduce out of the box.

**Comment by DanielCardonaRojas** [comment] 2021-11-12 00:07
Yeah you might be right I'm using NVchad as my base config

**Comment by akinsho** [comment] 2021-11-12 08:32
As far  as I know NVChad  has its own terminal plugin builtin,  so there's probably some other logic in your config that is also handling buffers and conflicting with this plugin

**Comment by DanielCardonaRojas** [comment] 2021-11-12 14:00
Jum.... I tried to search through nvchad but didn't find anything relevant although, I know its not the mapping since I'm executing the command manually (:ToggleTerm).  Looks like someone has suggested using toggleterm as the default plugin in NVChad, would be great, since there is no support for reopening the same terminal buffer currently: 

https://github.com/NvChad/NvChad/issues/489

**Comment by akinsho** [comment] 2021-11-12 14:18
@DanielCardonaRojas I think they used to use it but decided to move away from it for some reason, there was an issue here where I spoke to some people working on that project, and they ended up moving to their own implementation, so I wouldn't be surprised if they set an autocommand or something that causes this. In either case, I don't think the issue is native to this plugin, though.

**Comment by zbirenbaum** [comment] 2021-11-17 03:49
I use NvChad too and have no issues. My config and relevant portion in init.lua are posted here:
https://github.com/NvChad/NvChad/issues/489#issuecomment-971146933

**Comment by DanielCardonaRojas** [comment] 2021-11-26 02:23
Finally found the issue, what worked for me was commenting out the following auto command line in nvchad default config: 

> core/autocmds.lua
```lua
vim.cmd [[ au TermOpen term://* setlocal nonumber norelativenumber | setfiletype terminal ]]
```

**Comment by akinsho** [comment] 2021-11-26 10:09
Yeah, that would be it, since toggleterm sets the terminal to `toggleterm` so changing it will undoubtedly cause all sorts of chaos. Going to close this out now then 👍🏿

**Closed by akinsho** 2021-11-26 10:09 UTC
