### ISSUE TITLE
"couldn't find a terminal to close" when toggling a split when a tab is open

### ISSUE THREAD

**Issue by ioreshnikov** [akinsho/toggleterm.nvim#141] opened 2022-01-11 10:20 UTC
Hey!

I've noticed a mildly annoying bug: if you open a terminal with `:ToggleTerm tab`, switch back to the original tab and then call `:ToggleTerm split`, then you get the error message from the subject. It works perfectly fine in the other order -- a split terminal is being converted into a tab one, but not vice versa.

Best,
Ivan

**Comment by akinsho** [comment] 2022-09-09 11:18
Thanks for raising this, sorry lost sight of this issue. Just reproduced this locally and is definitely a bug but tbh it's not immediately clear what the right behaviour should be, but I guess in keeping with the general logic, if you haven't specified a terminal, and you decide to run `Toggleterm direction=tab` then move to another tab and convert it to a `horizontal` split then only one terminal should be manipulated i.e. the last one opened.

#309 attempts to fix this, but working with some many layouts is fiddly, so please test it out and let me know how it works for you. If you notice the winhighlight bleeding through feel free to mention, but frankly that's an upstream bug with a fix in nightly, but a hack in stable which I don't want to add here. Will patch it for nightly, but leave it as is for stable till 0.8 is released.

**Comment by ioreshnikov** [comment] 2022-09-13 08:39
Oh man, I completely forgot about this! :)

> it's not immediately clear what the right behaviour should be

I agree. I remember at the time skimming the code and thinking that this behaviour might be intentional. The use-case I have might be a bit different from what the extension initially intended – instead of multiple terminals I just want to have one. 

> keeping with the general logic, if you haven't specified a terminal, and you decide to run Toggleterm direction=tab then move to another tab and convert it to a horizontal split then only one terminal should be manipulated i.e. the last one opened.

This sounds good. I will give it a try today.

**Comment by ioreshnikov** [comment] 2022-09-14 10:16
@akinsho I have just tested it and it seems to be working as intended. Thanks!

**Comment by akinsho** [comment] 2022-09-14 10:36
Cool, I've just merged this in 👍🏿

**Closed by akinsho** 2022-09-14 10:36 UTC

**Comment by ioreshnikov** [comment] 2022-09-14 10:53
@akinsho I've just discovered a bug:

* open nvim
* call `ToggleTerm tab`
* switch back to the original empty tab
* call `ToggleTerm tab` one more time
* the terminal tab stays there, but you cannot switch to it

**Comment by akinsho** [comment] 2022-09-14 17:02
Will have a look 👍🏿

**Comment by akinsho** [comment] 2022-09-15 08:19
@ioreshnikov I cannot reproduce this behaviour, when I follow the steps above it works fine. Althought it's important to clarify that the correct command is `ToggleTerm direction=tab` not `ToggleTerm tab` and the second command definitely doesn't need to have `tab` argument. The correct flow should be:

* `ToggleTerm direction=tab`
* `ToggleTerm`

Can you ensure that you have `hidden` enabled.

**Comment by ioreshnikov** [comment] 2022-09-15 08:25
> Althought it's important to clarify that the correct command is ToggleTerm direction=tab not ToggleTerm tab and the second command definitely doesn't need to have tab argument.

Yes, sorry, I didn't write the proper commands because I have them bound to key combinations I didn't bother to go and properly look up what is executed.

As to why you cannot reproduce it, I think it's just a rendering issue specific to my vim version. I've built it from a nightly some months ago once they've introduced `cmdheight=0` and didn't update it since then.
