### ISSUE TITLE
 Invalid argum ent stack traceback - in function '__newindex'

### ISSUE THREAD

**Issue by ianworth** [akinsho/toggleterm.nvim#269] opened 2022-07-16 10:51 UTC
I upgraded the toggleterm plugin to [91505816335a93b10f026409228aef5e8d48e6d9](https://github.com/akinsho/toggleterm.nvim/commit/91505816335a93b10f026409228aef5e8d48e6d9) and got the error

```
Error executing Lua callback: ...te/pack/packer/opt/toggleterm.nvim/lua/toggleterm/ui.lua:141: E474: Invalid argum
ent
stack traceback:
        [C]: in function '__newindex'
        ...te/pack/packer/opt/toggleterm.nvim/lua/toggleterm/ui.lua:141: in function 'hl_term'
        ...k/packer/opt/toggleterm.nvim/lua/toggleterm/terminal.lua:414: in function 'open'
        .../site/pack/packer/opt/toggleterm.nvim/lua/toggleterm.lua:184: in function 'exec'
        .../site/pack/packer/opt/toggleterm.nvim/lua/toggleterm.lua:161: in function 'exec_command'
        .../site/pack/packer/opt/toggleterm.nvim/lua/toggleterm.lua:426: in function <.../site/pack/packer/opt/tog
gleterm.nvim/lua/toggleterm.lua:426>
```

When I run the command

    2TermExec dir="%:p:h" cmd="git push && exit 0" size=6

When I rolled back to commit before https://github.com/akinsho/toggleterm.nvim/commit/bd2b6f67f03566e68215442680ccb3b7d17efcde I do not get this error.

I'm on 0.7.2 (not nightly)

❯ nvim -v
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui

Thanks for awesome plugin BTW

**Comment by akinsho** [comment] 2022-07-16 11:53
Looks like a duplicate of #268, the latest commit should have fixed it

**Comment by ianworth** [comment] 2022-07-16 11:54
Ah - thx, I should have checked that - latest commit works good for me.

**Closed** 2022-07-16 11:54 UTC
Labels: duplicate
