### ISSUE TITLE
Toggleterm open and closes immediately

### ISSUE THREAD

**Issue by zephaniahong** [akinsho/toggleterm.nvim#371] opened 2022-12-17 02:27 UTC
Hi! Whenever I try to open toggle term, I see a flash of the terminal then it immediately disappears again. I do not have any errors whatsoever when i check :messages.
I am using it on LunarVim. 
OS: MacOS

https://user-images.githubusercontent.com/33389011/208219289-dc9e2e99-b2d4-4826-90fc-76402c474b06.mov

**Comment by akinsho** [comment] 2022-12-18 23:14
@zephaniahong this isn't currently a bug impacting the plugin in general as myself and other users would also have noticed this. This is *very likely* directly related to your configuration. Please try to reproduce this issue with *only a minimal init.lua* i.e. only this plugin and no configuration at all.

I'm going to close this out as I'm 90+% certain this does not relate to this plugin as I get issues similar to this which are usually due to a user's configuration issues which I cannot spare the time to investigate

**Closed by akinsho** 2022-12-18 23:14 UTC

**Comment by zephaniahong** [comment] 2022-12-28 11:07
In case anyone has this issue as well, I found out that I had some incorrect zsh environment variable in my .zshrc.

**Comment by istudyatuni** [comment] 2023-02-02 19:44
For me - enabled `virtualenvwrapper` plugin for oh-my-zsh

**Comment by somtodev** [comment] 2024-01-23 15:40
> @zephaniahong this isn't currently a bug impacting the plugin in general as myself and other users would also have noticed this. This is _very likely_ directly related to your configuration. Please try to reproduce this issue with _only a minimal init.lua_ i.e. only this plugin and no configuration at all.
> 
> I'm going to close this out as I'm 90+% certain this does not relate to this plugin as I get issues similar to this which are usually due to a user's configuration issues which I cannot spare the time to investigate

100%
I had same issue
vim.opt.shell = 'gnome-terminal(or whatever you have in here)' (removed this and it would work)
