### ISSUE TITLE
Question: is it possible to read input from a telescope picker?

### ISSUE THREAD

**Issue by metalelf0** [akinsho/toggleterm.nvim#132] opened 2021-12-21 09:41 UTC
Hi, I'm using toggleterm to open a terminal with lazygit in it, as in the README.

I'd like to be able to input gitmojis (https://gitmoji.dev/) when inside the lazygit commit dialog.

I tried setting up a mapping for the new terminal, as in the README, to toggle the [telescope-symbols](https://github.com/nvim-telescope/telescope-symbols.nvim) picker:

```lua
function _G.set_terminal_keymaps()
  local opts = {noremap = true}
  vim.api.nvim_buf_set_keymap(0, 't', '<esc>', [[<C-\><C-n>]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', 'jk', [[<C-\><C-n>]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-h>', [[<C-\><C-n><C-W>h]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-j>', [[<C-\><C-n><C-W>j]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-k>', [[<C-\><C-n><C-W>k]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-l>', [[<C-\><C-n><C-W>l]], opts)
  vim.api.nvim_buf_set_keymap(0, 't', '<C-g>', "<cmd>lua require('telescope.builtin').symbols{ sources = {'gitmoji'} }<CR>", opts)
end
```

But when I hit `<C-g>` I do see the telescope window, but the selected text is sent to the previous buffer, instead of the terminal, and the terminal with lazygit is closed.

I think this is because both telescope and toggleterm use "the same floating window", and only one floating window can exist at a time, but it's just a wild assumption. Am I right? Do you know if there's any workaround?

Thanks and keep up the great work :)

**Comment by akinsho** [comment] 2021-12-31 10:19
Hi @metalelf0, yep, so I think this would be caused by overlapping floating window plugins that both work largely by assuming they are the only floating windows visible and hiding when they are not focused. This is a pretty common pattern. TBH, trying to get them to play together I think would require an unpleasant amount of work/workarounds. I don't really have any suggestions here, since I don't know of any floating window plugins that are able to handle working together like this. I think it's likely to be too much complexity to manage within this plugin

**Comment by akinsho** [comment] 2022-01-25 08:49
Going to close this out since I don't really know that I can solve this but if someone finds this issue and wants to have a go happy to reopen to discuss

**Closed by akinsho** 2022-01-25 08:49 UTC
